---
title: "App_4250_Analysis"
author: "WANG Yuexiang"
date: "29 octobre 2015"
output: html_document
---

## 0 Segmentation
```{r, echo = FALSE, cache = TRUE, fig.width = 10, fig.height = 4, warning = FALSE}
ggplot(Ref) + geom_bar(aes(ord, fill = as.factor(Seg)), binwidth = 200) + ggtitle("Distribution of Segment by User")

ggplot(Ref) + geom_bar(aes(noPsg, fill = as.factor(Seg)), binwidth = 100) + ggtitle("Distribution of Segment by Number of passage")

```

## 1 Geographic Model

### 1.0 Daily Passage

```{r, echo = FALSE, cache = TRUE, fig.width = 10, fig.height = 4, warning = FALSE}
ggplot(t.DailyPassage) + 
  geom_bar(aes(x = noByDay,y= (..count..)/sum(..count..),
                                      fill=as.factor(no)),binwidth = 32) +
  ylab("Percentage") + ggtitle("Distribution of number of passages by Day")

ggplot(t.DailyPassage) + 
  geom_bar(aes(x = noByDay,y= (..count..)/sum(..count..),
               fill=as.factor(no)),binwidth = 1) +
  ylab("Percentage") + ggtitle("Distribution of number of passages by Day") +
  facet_wrap(~Seg)
```

### 1.1 Most and Second most frequented Sor

```{r, echo = FALSE, cache = TRUE, fig.width = 10, fig.height = 4, warning = FALSE}

```


### 1.2 Most and Second most frequented Sor

```{r, echo = FALSE, cache = TRUE, fig.width = 10, fig.height = 4, warning = FALSE}
ggplot(temp.noGare) + geom_point(aes(maxPerS, secPerS + maxPerS)) + ggtitle("1st & 2nd most frequented Transactions")
ggplot(temp.noGare) + geom_point(aes(maxPerS, secPerS + maxPerS, size = noGS)) + ggtitle("1st & 2nd most frequented Transactions with noPassage")
ggplot(temp.noGare) + 
  geom_point(aes(maxPerS, secPerS + maxPerS, col = as.factor(result), alpha = .2)) +
  ggtitle("1st & 2nd most frequented Transactions with Result")

ggplot(temp.noGare) + 
  geom_point(aes(maxPerS, secPerS + maxPerS, col = as.factor(result), alpha = .2)) +
  facet_wrap(~Seg) +
  ggtitle("1st & 2nd most frequented Transactions with Segmentation")
```

### 1.3 Most frequented Entr & Sor

```{r, echo = FALSE, cache = TRUE, fig.width = 10, fig.height = 4, warning = FALSE}
  
ggplot(temp.noGare) + 
  geom_density(aes(maxPerE, col = "1")) +
  geom_density(aes(maxPerE + secPerE, col = "1+2")) +
  geom_density(aes(maxPerE + secPerE + thrPerE, col = "1+2+3")) +
  geom_density(aes(maxPerE + secPerE + thrPerE + fouPerE, col = "1+2+3+4")) +
  xlab("Per") +
  ggtitle("Distribution of most frequent Entr")

ggplot(temp.noGare) + 
  geom_density(aes(maxPerS, col = "1")) +
  geom_density(aes(maxPerS + secPerS, col = "1+2")) +
  geom_density(aes(maxPerS + secPerS + thrPerS, col = "1+2+3")) +
  geom_density(aes(maxPerS + secPerS + thrPerS + fouPerS, col = "1+2+3+4")) +
  xlab("Per") +
  ggtitle("Distribution of most frequent Sor")
```

```{r, echo = FALSE, cache = TRUE, fig.width = 10, fig.height = 10, warning = FALSE}
g2 <- ggplot(temp.noGare) +
  geom_density(aes(maxPerS, col = "1")) +
  geom_density(aes(maxPerS + secPerS, col = "1+2")) +
  geom_density(aes(maxPerS + secPerS + thrPerS, col = "1+2+3")) +
  geom_density(aes(maxPerS + secPerS + thrPerS + fouPerS, col = "1+2+3+4")) +
  xlab("Per") +
  facet_wrap(~Seg, ncol = 1)

g1 <- ggplot(temp.noGare) +
  geom_density(aes(maxPerE, col = "1")) +
  geom_density(aes(maxPerE + secPerE, col = "1+2")) +
  geom_density(aes(maxPerE + secPerE + thrPerE, col = "1+2+3")) +
  geom_density(aes(maxPerE + secPerE + thrPerE + fouPerE, col = "1+2+3+4")) +
  xlab("Per")+
  facet_wrap(~Seg, ncol = 1)

grid.arrange(g1,g2, ncol = 2, main = "Distribution of most frequent Entr & Sor by Segmentation")
```


### 1.3 Example ID = 1

```{r, echo = FALSE, cache = TRUE, fig.width = 10, fig.height = 4, warning = FALSE}
t <- transaction2 %>% filter(ID == 1)

t1 <- gares %>% transmute(Entr = Cde, Elng= Lng, Elat = Lat)
t2 <- left_join(t, t1)
t1 <- gares %>% transmute(Sor = Cde, Slng= Lng, Slat = Lat)
t <- left_join(t2, t1)

ggplot(t) + 
  geom_point(aes(Elng, Elat, col ="Entr")) +
  geom_point(aes(Slng, Slat, col ="Sor")) +
  geom_segment(aes(x=Elng,xend=Slng,y=Elat,yend=Slat)) +
  geom_point(data= gares, aes(Lng,Lat, col = as.factor(Societe), alpha = .2))

t.OD <- t %>%
  group_by(Entr, Sor) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  arrange(desc(n)) %>%
  mutate(ord = row_number())

t1 <- t.OD %>% select(-n)
t <- inner_join(t,t1)

ggplot(t) + geom_point(aes(Date, TimeSor, col = as.factor(ord))) + theme(legend.position = "none")
ggplot(t %>% filter(ord < 8)) + geom_point(aes(Date, TimeSor, col = as.factor(ord)))

ggplot(t %>% filter(ord < 9)) + geom_point(aes(Date, TimeSor, col = as.factor(ord))) + facet_grid(Entr~Sor)


t3 <- t %>% filter(ord <3)
ggplot(t3) + geom_bar(aes(DOW, fill = as.factor(ord)), binwidth = 1, position = "dodge") + theme(legend.position = "none")
ggplot(t3) + geom_bar(aes(TimeSor, fill = as.factor(ord)), binwidth = 1, position = "dodge") + theme(legend.position = "none")

ggplot(t3) + geom_tile(aes(WOY,DOW, fill = as.factor(ord))) + facet_wrap(~ord, ncol = 1) + theme(legend.position = "none")

### gares
t.G <- temp.Gare %>% filter(ID == 1)
t1 <- gares %>% transmute(Gare = Cde, Lng, Lat)
t.G <- left_join(t.G, t1)

ggplot(t.G) + 
  geom_point(aes(Lng,Lat, size = perE)) +
  geom_point(data= gares, aes(Lng,Lat, col = as.factor(Societe), alpha = .2))

### chain
t.Chain <- t %>%
  group_by(Date, DOW) %>%
  arrange(TimeSor) %>%
  mutate(Dord = row_number())

t.Chain.summary <- t.Chain %>%
  summarise(last = n())

ggplot(t.Chain.summary) + geom_point(aes(Date, last)) + geom_path(aes(Date, last)) + ggtitle("ID = 1")
ggplot(t.Chain.summary) + geom_point(aes(Date, last, col = as.factor(DOW ))) + geom_path(aes(Date, last)) + facet_wrap(~DOW)+ ggtitle("ID = 1")
```