---
title: "Kmeans"
author: "WANG Yuexiang"
date: "Wednesday, June 24, 2015"
output: html_document
---

## Kmeans: ID1
```{r, cache=TRUE}
temp <- ID1[, c("Slng", "Slat")]
temp <- temp[!is.na(temp$Slng) & !is.na(temp$Slat), ]

names(temp)<-c("x","y")

ggplot(temp,aes(x,y))+geom_point()
gare.kmeans<-lapply(1:20,function(i){
  kmeans(temp[,c("x","y")],centers=i)
})

lapply(gare.kmeans,function(z) z$withinss)
gare.within.ss<-sapply(gare.kmeans, function(z) sum(z$withinss))

plot(1:20, type="b",xlab = "Number of clusters", ylab = "Within SS",gare.within.ss)
```

```{r, cache=TRUE,fig.width=5,fig.height=5}
# ## Nb of Clusters from 1 to 10
# cluster.colors<-lapply(gare.kmeans,function (z) z$cluster)
# 
# # library(plry)
#  l_ply(cluster.colors, function(colors){
#    plot(y~x,temp,col=colors,main=paste(nlevels(factor(colors))),pch=16)
#  })
```

## By ggplot
```{r, cache=TRUE,fig.width=5,fig.height=5}
l_ply(cluster.colors,
      function(colors) {
          plot.dat <- cbind(temp, cluster = factor(colors))
          gg.obj <- ggplot(plot.dat, aes(x,y, color = cluster)) +
              geom_point() + labs(title = paste(nlevels(factor(colors))))
          print(gg.obj)
      })
```
