---
title: "UserProfile_ID1"
date: "Wednesday, June 17, 2015"
output: html_document
---
```{r, echo=FALSE,cache=TRUE}
# ggplot(ID1,aes(Sor))+geom_bar()
Sor<-count(ID1,"Sor")
Entr<-count(ID1,"Entr")
OD<-count(ID1,c("Entr","Sor"))
OD<-OD[order(OD$freq,decreasing=TRUE),]

names(Sor)[1]<-"Cde"
names(Entr)[1]<-"Cde"
Sor<-merge(x=Sor,gares_geo,by="Cde")
Entr<-merge(Entr,gares_geo,by="Cde")
Entr<-Entr[order(Entr$freq,decreasing=TRUE),]
Sor<-Sor[order(Sor$freq,decreasing=TRUE),]
```

## Users_1
```{r set-options, echo=FALSE, cache=TRUE}
options(width=100) 
options(cache=FALSE)
options(echo=FALSE)
```
#### General

1. Total Nb of Trx: **`r nrow(ID1)`**
2. Nb of Trx by Result of Simple Model:
```{r, echo=FALSE,cache=TRUE}
count(ID1,"Predicted")
```
3. Nb of Trx by zone (zone: 25004210-25004220)
```{r, echo=FALSE,cache=TRUE}
count(ID1,"zone")
```

4. Nb of Trx by Result of Simple Model on Zone:
```{r, echo=FALSE,cache=TRUE}
count(ID1,"Pred_Z")
```


### Result of Simple Model on OD & Zone
```{r, echo=FALSE,cache=TRUE,fig.width= 10, fig.height=3}
p1<-ggplot(ID1,aes(Hour,fill=as.factor(Predicted)))+geom_bar(binwidth=1)+
  scale_fill_discrete(name="Predicted") +
	theme(legend.position=c(.9,.8),plot.title = element_text(size=15, face="bold"))+
	ggtitle("Simple Model Result")
p2<-ggplot(ID1,aes(Hour,fill=as.factor(Pred_Z)))+geom_bar(binwidth=1)+
  scale_fill_discrete(name="Predicted") +
	theme(legend.position=c(.9,.8),plot.title = element_text(size=15, face="bold"))+
	ggtitle("Simple Model on Zone")
grid.arrange(p1,p2,ncol=2) 
```


```{r, echo=FALSE,cache=TRUE,fig.width= 15, fig.height=8}
p1<-ggplot(ID1,aes(Date,fill=as.factor(Predicted)))+geom_bar(binwidth=1)+
  scale_fill_discrete(name="Predicted")+
	theme(legend.position=c(.97,.85),plot.title = element_text(size=20, face="bold"))+
	ggtitle("Simple Model Result")
p2<-ggplot(ID1,aes(Date,fill=as.factor(Pred_Z)))+geom_bar(binwidth=1)+
  scale_fill_discrete(name="Predicted")+
	theme(legend.position=c(.97,.85),plot.title = element_text(size=20, face="bold"))+
	ggtitle("Simple Model on Zone")
grid.arrange(p1,p2,ncol=1) 
```

### Viz of Gares & OD

```{r, echo=FALSE,cache=TRUE,fig.width= 10, fig.height=5, warning=FALSE}
p1<-ggplot(Entr)+geom_point(aes(Lng, Lat,size=freq), col="Green")+
    geom_point(data=gares_geo,aes(Lng,Lat),size=3,alpha=.2,shape=3)+
    ylim(c(42,46.5))+xlim(c(-1.5,7.5))+
    theme(legend.position=c(.9,.9),plot.title = element_text(size=20, face="bold"))+
  	ggtitle("Entr")
p2<-ggplot(Sor)+geom_point(aes(Lng, Lat,size=freq), col="Red")+
    geom_point(data=gares_geo,aes(Lng,Lat),size=3,alpha=.2,shape=3)+
    geom_point(data=gare_SO,aes(Lng, Lat, color="S.O."), size=3, shape=3)+
    ylim(c(42,46.5))+xlim(c(-1.5,7.5))+
    theme(legend.position=c(.9,.9),plot.title = element_text(size=20, face="bold"))+
	  ggtitle("Sor")
grid.arrange(p1,p2,ncol=2)
```

```{r, echo=FALSE,cache=TRUE,fig.width= 10, fig.height=10, warning=FALSE}
ggplot()+ 
  geom_segment(data=ID1,aes(x=Elng, y=Elat,xend=Slng, yend=Slat,color=as.factor(zone)), 
               alpha=.3,lwd=1,arrow=arrow(length = unit(0.1,"cm")))+
  scale_color_discrete(name="Zone") +
  geom_point(data=Sor,aes(Lng, Lat,size=freq), col="Red")+
  geom_point(data=gares_geo,aes(Lng,Lat),size=3,alpha=.2,shape=3)+
  geom_point(data=gare_SO,aes(Lng, Lat, color="S.O."), size=3, shape=3)+
  ylim(c(42,46.5))+xlim(c(-1.5,7.5))+
  theme(legend.position=c(.95,.9),plot.title = element_text(size=20, face="bold")) +
  ggtitle("Sor & OD")
```

#### Gares & ODs : frequently passed
```{r, echo=TRUE,cache=TRUE}
Entr[1:10,-(7:8)] 
Sor[1:10,-(7:8)]
OD[1:10,]
```

