---
title: "All"
author: "WANG Yuexiang"
date: "6 juillet 2015"
output: html_document
---

## 1
```{r, width=80, fig.width=12,fig.height=150,cache=TRUE}
ggplot(trx.2014[trx.2014$Label %in% c(1:100),]) + 
  geom_tile(aes(Date, Hour)) + 
  facet_wrap(~Label, ncol = 2) + theme(legend.position = "none")
```

## 201
```{r, width=80, fig.width=12,fig.height=150,cache=TRUE}
ggplot(trx.2014[trx.2014$Label %in% c(201:300),]) + 
  geom_tile(aes(Date, Hour)) + 
  facet_wrap(~Label, ncol = 2) + theme(legend.position = "none")
```

## 1901
```{r, width=80, fig.width=12,fig.height=150,cache=TRUE}
ggplot(trx.2014[trx.2014$Label %in% c(1901:2000),]) + 
  geom_tile(aes(Date, Hour)) + 
  facet_wrap(~Label, ncol = 2) + theme(legend.position = "none")
```

## 2901
```{r, width=80, fig.width=12,fig.height=150,cache=TRUE}
ggplot(trx.2014[trx.2014$Label %in% c(2901:3000),]) + 
  geom_tile(aes(Date, Hour)) + 
  facet_wrap(~Label, ncol = 2) + theme(legend.position = "none")
```

## 3901
```{r, width=80, fig.width=12,fig.height=150,cache=TRUE}
ggplot(trx.2014[trx.2014$Label %in% c(3901:4000),]) + 
  geom_tile(aes(Date, Hour)) + 
  facet_wrap(~Label, ncol = 2) + theme(legend.position = "none")
```

## 4901
```{r, width=80, fig.width=12,fig.height=150,cache=TRUE}

ggplot(trx.2014[trx.2014$Label %in% c(4901:5000),]) + 
  geom_tile(aes(Date, Hour)) + 
  facet_wrap(~Label, ncol = 2) + theme(legend.position = "none")
```